### ISSUE TITLE
Preppapacalapse

### ISSUE THREAD

**Issue by metalbaby13** [arramus/A21-Preppocalypse#2]
Cant find any acorns or pine nuts , Is this an issue?

**Comment by arramus** [comment]
Acorn flour/meal is made from the Oak tree seed (Oak Seed). Pine nuts are made from the Pine tree seed (Pine Seed). Both recipes can be made directly on the player in the same way as Corn Meal from Corn. The Acorn or Oaknut are the individual seeds hanging from the Oak tree. The Pine nuts are the seeds found as a cluster with the Pine Seed.

**Comment by metalbaby13** [comment]
Yes I understand that but there are no oak seeds or pine seeds when you
chop down trees believe me I have over 18000 thousand wood and not one seed.

**Comment by arramus** [comment]
In response to lack of seeds you are experiencing, here are a few images to demonstrate seed drops from an Oak Tree and Pine Tree immediately after joining a new World.

The test environment is as follows:

A21.1(b16)
A21-Preppocalypse build 7cb08da83abda9f3bcd9e2aaeee7ea4603dd5911 (The latest build)
6K RWG World

Completing a tree harvest on a 1200 HP Oak Tree. This displays two Oak Seeds as the drop item.
![A21 1_2023-08-21_23-33-33](https://github.com/arramus/A21-Preppocalypse/assets/71211641/5296ce12-1e94-44fc-a65e-2051cd222d9a)

Completing a tree harvest on a 1200 HP Pine Tree. This displays two Pine Seeds as the drop item.
![A21 1_2023-08-21_23-34-07](https://github.com/arramus/A21-Preppocalypse/assets/71211641/85d40ae9-5789-4704-aec1-0bdfad11d714)

Confirmation of Tree Seeds dropped into inventory.
![A21 1_2023-08-21_23-34-15](https://github.com/arramus/A21-Preppocalypse/assets/71211641/a0c71a0d-0c24-4802-87eb-aad7df9016ee)

I was unable to experience the lack of Tree Seeds shared in the issue posting.

**Comment by metalbaby13** [comment]
I am no stranger to seed drops I am just saying I have experienced no seed
drops maybe the server owner down loaded  it wrong.

**Comment by arramus** [comment]
Maybe the server owner installed a no seed mod to reduce the amount of trees players are planting without realising the need for them in recipes.

This issue is closed as it cannot be verified with the load out parameters in the above test.

**Comment by metalbaby13** [comment]
Awesome, thanks for the update!
